name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Next.js app
        run: npm run build
      
      - name: Create root index.html
        run: |
          mkdir -p out
          cat > out/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>In Pharma Trading</title>
            <script>
              // Redirect to default locale
              const preferredLang = navigator.language?.split('-')[0];
              const supportedLangs = ['en', 'de', 'nl'];
              const defaultLang = supportedLangs.includes(preferredLang) ? preferredLang : 'en';
              window.location.replace('/' + defaultLang + '/');
            </script>
            <noscript>
              <meta http-equiv="refresh" content="0; url=/en/">
            </noscript>
          </head>
          <body>
            <p>Redirecting to <a href="/en/">In Pharma Trading</a>...</p>
          </body>
          </html>
          EOF
        
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "out" # Pre-built app content directory
          api_location: "" # Api source code path - optional
          output_location: "" # No additional output location needed since we're pointing directly to built files
          skip_app_build: true # Skip build since we already built the app
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
